apiVersion: v1
kind: Service
metadata:
  name: collabeditor-server
spec:
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    app: collabeditor-server
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: collabeditor-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: collabeditor-server
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http2_port=9000",
          "--backend=grpc://127.0.0.1:9090",
          "--service=collabeditor.endpoints.collabeditor-anton.cloud.goog",
          "--rollout_strategy=managed",
        ]
        ports:
          - containerPort: 9000
      - name: collabeditor-server
        image: gcr.io/collabeditor-anton/collabeditor-server:1.1
        ports:
          - containerPort: 9090
